export const technological = [
  {
    title: 'myoffice_tab_title',
    description: 'myoffice_tab_description',
    country: 'myoffice_tab_country',
    category: 'myoffice_tab_category',
    link: 'myoffice.ru',
    image: '/images/partners/myoffice_icon.png',
    https: true,
  },
  {
    title: 'fasttrack_tab_title',
    description: 'fasttrack_tab_description',
    country: 'fasttrack_tab_country',
    category: 'fasttrack_tab_category',
    link: 'fstrk.io',
    image: '/images/partners/fasttrack_icon.jpeg',
    https: true,
  },
  {
    title: 'mtraining_tab_title',
    description: 'mtraining_tab_description',
    country: 'mtraining_tab_country',
    category: 'mtraining_tab_category',
    link: 'mastertraining.it',
    image: '/images/partners/mtraining_icon.png',
    https: true,
  },
  {
    title: 'chatme_tab_title',
    description: 'chatme_tab_description',
    country: 'chatme_tab_country',
    category: 'chatme_tab_category',
    link: 'chatme.ai',
    image: '/images/partners/chatme_icon.svg',
    https: true,
  },
  {
    title: 'basealt_tab_title',
    description: 'basealt_tab_description',
    country: 'basealt_tab_country',
    category: 'basealt_tab_category',
    link: 'www.basealt.ru',
    image: '/images/partners/basealt_icon.png',
    https: true,
  },
  {
    title: 'omp_tab_title',
    description: 'omp_tab_description',
    country: 'omp_tab_country',
    category: 'omp_tab_category',
    link: 'omprussia.ru',
    image: '/images/partners/omp_icon.svg',
    https: false,
  },
];

export const business = [
  {
    title: 'beclever_tab_title',
    description: 'beclever_tab_description',
    country: 'beclever_tab_country',
    category: 'beclever_tab_category',
    link: 'beclever.online',
    image: '/images/partners/beclever_icon.png',
    https: true,
  },
  {
    title: 'softline_tab_title',
    description: 'softline_tab_description',
    country: 'softline_tab_country',
    category: 'softline_tab_category',
    link: 'softline.ru',
    image: '/images/partners/softline_icon.png',
    https: true,
  },
  {
    title: 'rb_tab_title',
    description: 'rb_tab_description',
    country: 'rb_tab_country',
    category: 'rb_tab_category',
    link: 'rbtechnologies.ru',
    image: '/images/partners/rb_icon.png',
    https: false,
  },
  {
    title: 'dm_tab_title',
    description: 'dm_tab_description',
    country: 'dm_tab_country',
    category: 'dm_tab_category',
    link: 'www.dm-solutions.ru',
    image: '/images/partners/dm_icon.png',
    https: false,
  },
  {
    title: 'swemel_tab_title',
    description: 'swemel_tab_description',
    country: 'swemel_tab_country',
    category: 'swemel_tab_category',
    link: 'www.swemel.ru',
    image: '/images/partners/swemel_icon.png',
    https: true,
  },
  {
    title: 'croc_tab_title',
    description: 'croc_tab_description',
    country: 'croc_tab_country',
    category: 'croc_tab_category',
    link: 'www.croc.ru',
    image: '/images/partners/croc_icon.svg',
    https: true,
  },
];
