name: Develop CI

on:
  push:
    branches:
      - 'develop'

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Pipline notify started
        run: |
          BUILD_NUMBER=$(git rev-list --count HEAD)
          curl --header 'Content-Type: application/json' --request POST \
          --data "{\"text\": \"👉🏾 Homepage build(develop) *#$BUILD_NUMBER*: pipeline started.\"}" \
          ${{ secrets.DIALOG_WEBHOOK }}
      - name: Build
        env:
          EMAIL_USER: ${{secrets.EMAIL_USER}}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          GHOST_ENDPOINT: ${{ secrets.GHOST_ENDPOINT }}
          GHOST_API_KEY: ${{ secrets.GHOST_API_KEY }}
          MAILCHIMP_KEY: ${{ secrets.MAILCHIMP_KEY }}
          MAILCHIMP_LIST_RU: ${{ secrets.MAILCHIMP_LIST_RU }}
          MAILCHIMP_LIST_EN: ${{ secrets.MAILCHIMP_LIST_EN }}
          GATSBY_GRAPHQL_IDE: playground
          DIALOG_WEBHOOK: ${{ secrets.DIALOG_WEBHOOK }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_DSN_PUBLIC: ${{ secrets.SENTRY_DSN_PUBLIC }}
        run: |
          npm ci
          npm run build
          BUILD_NUMBER=$(git rev-list --count HEAD)
          curl --header 'Content-Type: application/json' --request POST \
          --data "{\"text\": \"👌🏾 Homepage build(develop) *#$BUILD_NUMBER*: application build successful.\"}" \
          ${{ secrets.DIALOG_WEBHOOK }}
      - name: Upload app artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: public
      - name: Upload server artifact
        uses: actions/upload-artifact@v1
        with:
          name: server
          path: server

  build-docker:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download app artifact
        uses: actions/download-artifact@v1
        with:
          name: app
          path: public
      - name: Download server artifact
        uses: actions/download-artifact@v1
        with:
          name: server
          path: server
      - name: Build the Docker image
        env:
          DOCKER_IMAGE: docker.pkg.github.com/dialogs/homepage/homepage
          NODE_ENV: production
        run: |
          BUILD_NUMBER=$(git rev-list --count HEAD)
          VERSION=$(node -p "require('./package.json').version")
          IMAGE_VERSION="${VERSION}.$BUILD_NUMBER"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker build -t $DOCKER_IMAGE:$IMAGE_VERSION .
          docker tag $DOCKER_IMAGE:$IMAGE_VERSION $DOCKER_IMAGE:$IMAGE_VERSION
          docker push $DOCKER_IMAGE:$IMAGE_VERSION
          curl -X POST "https://${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_PASSWORD }}@jenkins.transmit.im/job/Web/job/landing-deploy-test/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}&app=demo&image=$DOCKER_IMAGE:$IMAGE_VERSION"
      - name: Docker image notify
        run: |
          BUILD_NUMBER=$(git rev-list --count HEAD)
          curl --header 'Content-Type: application/json' --request POST \
          --data "{\"text\": \"👌🏾 Homepage build(develop) *#$BUILD_NUMBER*: docker image ready. \"}" \
          ${{ secrets.DIALOG_WEBHOOK }}
      # - name: Deploy
      #   run: curl -X POST "https://${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_PASSWORD }}@jenkins.transmit.im/job/Web/job/landing-deploy/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}&app=demo&image=$DOCKER_IMAGE:$IMAGE_VERSION"
      - name: Deploy notify
        if: success()
        run: |
          BUILD_NUMBER=$(git rev-list --count HEAD)
          curl --header 'Content-Type: application/json' --request POST \
          --data "{\"text\": \"👌🏾 Homepage build(develop) *#$BUILD_NUMBER:* successfully deployed. \"}" \
          ${{ secrets.DIALOG_WEBHOOK }}
      - name: Exception
        if: failure()
        run: |
          BUILD_NUMBER=$(git rev-list --count HEAD)
          curl --header 'Content-Type: application/json' --request POST \
          --data "{\"text\": \"🖕🏾 Homepage build(develop) *#$BUILD_NUMBER:* pipeline failed. [More info](https://github.com/dialogs/dialog-web-platform/commit/${GITHUB_SHA}/checks)\"}" \
          ${{ secrets.DIALOG_WEBHOOK }}
